name 'conqueso'
maintainer 'Rapid7, LLC.'
maintainer_email 'eciramella@rapid7.com'
license 'Apache License'
description 'Installs/Configures the conqueso server'
long_description IO.read('README.md') rescue ''
version IO.read('VERSION') rescue '0.0.1'

depends 'apt'
depends 'build-essential', '1.4.2'
depends 'mysql', '4.0.20'
depends 'nodejs'
depends 'openssl', '1.1.0'
depends 'yum', '3.0.4'
depends 'logrotate', '~> 1.9.2'
